package com.bizeff.procurement.webapi.utility;
public enum Permission {

    // Requisition Management
    REQUISITION_CREATE, REQUISITION_TRACK, REQUISITION_VIEWPENDING_STATUS,

    // Purchase Order Management
    PURCHASE_ORDER_CREATE, PURCHASE_ORDER_APPROVE, PURCHASEORDER_RECEIVE,

    // Vendor Management
    Supplier_ADD, SUPPLIER_PERFORMANCE_VIEW, SUPPLIER_PROFILE_UPDATE,

    // Contract Management
    CONTRACT_CREATE, CONTRACTDETAILS_VIEW, CONTRACT_NOTIFY,

    // Invoice & Payment
    INVOICE_RECONCILE, PAYMENTRECONCILATIONHISTORY_VIEWTOTAL, PAYMENTRECONCILATIONHISTORY_VIEWPAYMENTDATEBASED,PAYMENTRECONCILATIONHISTORY_VIEWSTATUS_BASED, PAYMENTRECONCILATIONHISTORY_VIEWSUPPLIER_BASED, PAYMENTAPPROVE_NOTIFICATION,

    // Supplier Performance
    PERFORMANCEREPORT_GENERATE, SUPPLIERPERFORMANCE_REVIEW,
    SUPPLIERPERFORMANCEMETRICS_VIEW,

    // Reporting
    APPROVEDPURCHASEORDERREPORT_GENERATE, CUSTOMIZEDDASHBOARD_CREATE, REPORTDATA_EXPORT,
}